### ISSUE TITLE
Integration does not reconnect to ph-803w after it goes offline

### ISSUE THREAD

**Issue by roobre** [dala318/python_ph803w#20]
Hey there!

First of all, let me give you a huge thank you fork setting this up! My plan when I bought this was to use the node-mqtt adapter, but this solution looks substantially better to me :)

Now, I've been facing a problem in a situation where, due to some limitations of my electrical installation, I'm not able to have the ph-803w meter powered up all the time. It is roughly on for several hours per day, in one hour chunks.

This seems to be causing a problem with the integration. When the ph-803w is on, if I restart homeassistant, I very quickly start to get data from it. Then, the device turns off, and I stop receiving data (to be expected). Later on, the ph-803w will get turned on again, but no data is being received by the integration. Restarting HASS causes data to be picked up again.

The ph-803w has a static lease on my network, and I can ping the device every time it is on.

Do you know if this is expected behavior? Could it be a way for the integration to retry to connect every couple of minutes or so, simply forever until it succeeds?

I'm not a python expert but maybe I could lend a hand implementing this, provided some pointers on where to start :)

**Comment by roobre** [comment]
Seems like it's possible to raise a `PlatformNotReady` exception that will cause HASS to retry setup: https://developers.home-assistant.io/docs/integration_setup_failures#integrations-using-async_setup_platform

Example code here: https://github.com/home-assistant/example-custom-config/blob/master/custom_components/example_light/light.py#L28

This would, however, require to use setup_platform rather than setup. Not sure if this is a problem.

**Comment by roobre** [comment]
After studying the codebase a little, it seems that what I linked above won't work, as we're polling the device on a separate thread.

We could, perhaps, move the device initialization logic from the thread's `__init__`:

https://github.com/dala318/python_ph803w/blob/ef88bf097457cf824dd3e473c227461279cf05fb/__init__.py#L50-L57

to somewhere else, perhaps some where here https://github.com/dala318/python_ph803w/blob/ef88bf097457cf824dd3e473c227461279cf05fb/__init__.py#L110

**Comment by dala318** [comment]
Hi. Nice to see this being used and improved. I kind of abandoned this project, or at least paused it, since I bought a BlueConnect and had it integrated.
Feel free to modify as you like :)

**Comment by roobre** [comment]
That's good to know! For now I'm not 100% sure I'll improve it a lot, I'll probably focus on that use case and let it be :)

I've been testing the PR on my setup for several hours and seems to be working fine, after some more testing I might request a review from you if that's OK :)

**Comment by dala318** [comment]
An alternative is to add a config variable that disables usage of the background thread and instead polls the devices from HASS request, and on every request re-initialize the communication.
What I've seen is that quite soon after communication is initialized you get a reading.

**Comment by dala318** [comment]
When the power to the device is lost do you get the ErrorConnection interrupt, and end up on the 6000s retry-delay?
If so, try removing the the higher delays in the list or modify the times and see if it helps you?

**Comment by roobre** [comment]
> An alternative is to add a config variable that disables usage of the background thread and instead polls the devices from HASS request, and on every request re-initialize the communication.

Problem with this is that we would get a less tighter feedback on the relay status, right? I think I read a comment in the code regarding that.

**Comment by roobre** [comment]
https://github.com/dala318/python_ph803w/pull/21 marked ready for review :)
