### ISSUE TITLE
Integration in Home assistant

### ISSUE THREAD

**Issue by senya1312** [dala318/python_ph803w#22]
Hello. Please help me integrate the PH 803 into Home Assistant. I don’t know what cloning means.

**Comment by dala318** [comment]
You clone if by the two command proposals just below that line in the read-me, but you need a terminal for that.
As alternative you can download the repo and unzip in your config/custom_components folder on Home Assistant
![image](https://github.com/dala318/python_ph803w/assets/20300390/06f3349f-2dfd-4079-b242-6b2d488a1ed5)

**Comment by senya1312** [comment]
Thank you very much. Everything worked out for me
